version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
      - JWT_SECRET=change-me
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
